# Generated by Django 4.2 on 2023-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='')),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone_emergencia', models.CharField(max_length=20)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('historico_familiar', models.TextField(blank=True, null=True)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Cadastro',
            },
        ),
    ]
