# Generated by Django 4.2 on 2023-06-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Cadastro',
        ),
    ]
