# Generated by Django 4.2.1 on 2023-06-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_rename_cadastro_aluno_alter_aluno_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name_plural': 'Aluno'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_matricula',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem_aprovacao', models.IntegerField()),
                ('media_frequencia', models.FloatField()),
                ('matricula_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=20)),
                ('peso', models.IntegerField()),
                ('nota_1', models.FloatField()),
                ('nota_2', models.FloatField()),
                ('nota_3', models.FloatField()),
                ('nota_4', models.FloatField()),
                ('nota_final', models.FloatField()),
                ('matricula_aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('presenca', models.BooleanField()),
                ('falta', models.IntegerField()),
                ('matricula_aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.aluno')),
            ],
        ),
    ]
