# Generated by Django 4.2.1 on 2023-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='media_notas',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='matricula_aluno',
            field=models.IntegerField(unique=True),
        ),
    ]
