# Generated by Django 4.2.1 on 2023-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_turma_cod_turma_alter_turma_matricula_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome_turma',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
