# Generated by Django 4.2.1 on 2023-06-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_turma_nome_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='matricula_aluno',
            field=models.IntegerField(unique=True),
        ),
    ]
