# Generated by Django 4.2.1 on 2023-06-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_aluno_numero_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='matricula_aluno',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma'),
        ),
    ]
