# Generated by Django 4.2.1 on 2023-06-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_aluno_cod_turma_alter_aluno_numero_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cod_turma',
        ),
    ]
