# Generated by Django 4.2.1 on 2023-06-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_remove_aluno_cod_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cod_turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma'),
            preserve_default=False,
        ),
    ]
