# Generated by Django 4.2.1 on 2023-06-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_aluno_cod_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cod_turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='cod_turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='media_frequencia',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='nome_turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='porcentagem_aprovacao',
        ),
    ]
