# Generated by Django 4.2.1 on 2023-06-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_remove_aluno_cod_turma_remove_turma_cod_turma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='media_notas',
        ),
    ]
