# Generated by Django 4.2.1 on 2023-06-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_remove_turma_media_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='numero_matricula',
        ),
    ]
