# Generated by Django 4.2.1 on 2023-06-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_remove_aluno_numero_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero_matricula',
            field=models.IntegerField(default=233, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula_aluno',
            field=models.ForeignKey(default=233, on_delete=django.db.models.deletion.CASCADE, to='cadastro.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='media_frequencia',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='media_notas',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='porcentagem_aprovacao',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
