# Generated by Django 4.2.1 on 2023-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_remove_turma_matricula_aluno_aluno_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome_turma',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
