# Generated by Django 4.2.1 on 2023-06-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_turma_nome_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='numero_matricula',
        ),
    ]
