# Generated by Django 4.2.1 on 2023-06-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_remove_turma_numero_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
